name: Lint

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Black
        uses: psf/black@stable